import { Job } from "@/types";

export const DUMMY_JOBS: Job[] = [
  {
    id: "1",
    title: "Senior Frontend Engineer",
    location: "Bangalore, India",
    status: "published",
    jobType: "full_time",
    workMode: "remote",
    applicationCount: 42,
    createdAt: new Date().toISOString(),
    department: { id: "d1", name: "Engineering" },
  },
  {
    id: "2",
    title: "Product Designer",
    location: "Mumbai, India",
    status: "draft",
    jobType: "full_time",
    workMode: "hybrid",
    applicationCount: 0,
    createdAt: new Date().toISOString(),
    department: { id: "d2", name: "Design" },
  },
  {
    id: "3",
    title: "Marketing Manager",
    location: "Delhi, India",
    status: "pending_approval",
    jobType: "contract",
    workMode: "onsite",
    applicationCount: 12,
    createdAt: new Date().toISOString(),
    department: { id: "d3", name: "Marketing" },
  },
  {
    id: "4",
    title: "Backend Developer (Node.js)",
    location: "Remote",
    status: "closed",
    jobType: "full_time",
    workMode: "remote",
    applicationCount: 89,
    createdAt: new Date().toISOString(),
    department: { id: "d1", name: "Engineering" },
  },
  {
    id: "5",
    title: "HR Generalist",
    location: "Pune, India",
    status: "published",
    jobType: "internship",
    workMode: "onsite",
    applicationCount: 5,
    createdAt: new Date().toISOString(),
    department: { id: "d4", name: "HR" },
  },
];